/// Business notification types are hidden from Mainstage listeners. Keep this
/// list aligned with the server's notification audience policy; public event,
/// table, social and media notifications are separate contracts.
abstract final class NotificationAudiencePolicy {
  static const businessTypes = <String>{
    'STUDIO_RESERVATION_CREATED',
    'STUDIO_RESERVATION_CONFLICTING_REQUESTS',
    'STUDIO_RESERVATION_APPROVED',
    'STUDIO_RESERVATION_REJECTED',
    'STUDIO_RESERVATION_CANCELLED_BY_CUSTOMER',
    'STUDIO_RESERVATION_CANCELLED_BY_STUDIO',
    'VENUE_APPLICATION_REJECTED',
    'ARTIST_VENUE_LINK_APPLICATION_REQUEST',
    'ARTIST_VENUE_LINK_APPLICATION_ACCEPT',
    'ARTIST_VENUE_LINK_APPLICATION_REJECT',
    'EVENT_PERFORMER_ADDED',
    'EVENT_PERFORMER_APPROVAL_REQUESTED',
    'EVENT_PERFORMER_APPROVED',
    'EVENT_PERFORMER_REJECTED',
    'EVENT_VENUE_APPROVAL_REQUESTED',
    'EVENT_VENUE_APPROVED',
    'EVENT_VENUE_REJECTED',
    'BAND_INVITE_RECEIVED',
    'BAND_INVITE_ACCEPTED',
    'BAND_INVITE_REJECTED',
    'BAND_MEMBER_REMOVED',
    'BAND_MEMBER_LEFT',
    'COLLAB_APPLICATION_RECEIVED',
    'COLLAB_APPLICATION_ACCEPTED',
    'COLLAB_APPLICATION_REJECTED',
    'COLLAB_APPLICATION_WITHDRAWN',
    'COLLAB_APPLICATION_INVALIDATED',
    'COLLAB_LISTING_EXPIRED',
    'COLLAB_JOB_COMPLETION_REQUESTED',
    'COLLAB_JOB_COMPLETED',
    'COLLAB_REVIEW_RECEIVED',
    'COLLAB_LISTING_REMOVED',
    'COLLAB_REPORT_RESOLVED',
  };

  static bool visibleToListener(String type) =>
      !businessTypes.contains(type.trim().toUpperCase());
}
