package com.berkayb.soundconnect.soundconnect_23_12_25codx

/** Current parser contract, shared by JVM metadata and real Android bridge tests. */
internal object NativePushOpenCases {
    val types = listOf("DM_NEW_MESSAGE",
        "ARTIST_VENUE_LINK_APPLICATION_REQUEST", "ARTIST_VENUE_LINK_APPLICATION_ACCEPT", "ARTIST_VENUE_LINK_APPLICATION_REJECT",
        "EVENT_PERFORMER_APPROVAL_REQUESTED", "EVENT_PERFORMER_APPROVED", "EVENT_PERFORMER_REJECTED",
        "VENUE_APPLICATION_APPROVED", "VENUE_APPLICATION_REJECTED",
        "STUDIO_RESERVATION_CREATED", "STUDIO_RESERVATION_CONFLICTING_REQUESTS", "STUDIO_RESERVATION_APPROVED",
        "STUDIO_RESERVATION_REJECTED", "STUDIO_RESERVATION_CANCELLED_BY_CUSTOMER", "STUDIO_RESERVATION_CANCELLED_BY_STUDIO",
        "OVERTHINKING_REVEAL_REQUEST_RECEIVED", "OVERTHINKING_REVEAL_REQUEST_APPROVED", "OVERTHINKING_REVEAL_REQUEST_REJECTED",
        "COLLAB_APPLICATION_RECEIVED", "COLLAB_APPLICATION_ACCEPTED", "COLLAB_APPLICATION_REJECTED",
        "COLLAB_APPLICATION_WITHDRAWN", "COLLAB_APPLICATION_INVALIDATED", "COLLAB_LISTING_EXPIRED",
        "COLLAB_JOB_COMPLETION_REQUESTED", "COLLAB_JOB_COMPLETED", "COLLAB_REVIEW_RECEIVED", "COLLAB_LISTING_REMOVED", "COLLAB_REPORT_RESOLVED",
        "TABLE_JOIN_REQUEST_RECEIVED", "TABLE_JOIN_REQUEST_APPROVED", "TABLE_JOIN_REQUEST_REJECTED",
        "TABLE_PARTICIPANT_LEFT", "TABLE_REMOVED", "TABLE_CANCELLED", "TABLE_EXPIRED",
        "SOCIAL_NEW_FOLLOWER", "SOCIAL_NEW_BAND_FOLLOWER", "SOCIAL_LIKE", "SOCIAL_COMMENT",
        "BAND_INVITE_RECEIVED", "BAND_INVITE_ACCEPTED", "BAND_INVITE_REJECTED", "BAND_MEMBER_REMOVED", "BAND_MEMBER_LEFT")
}
